workflows:
  android:
    name: Android Build
    environment:
      java: 11
    scripts:
            - name: Install Gradle
        script: |
          brew install gradle
            - name: Build APK
        script: |
          gradle assembleDebug
    artifacts:
            - app/build/outputs/apk/debug/app-debug.apk
